name: AWS EC2 and ALB Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install AWS CLI (if needed)
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # Step 4: Deploy EC2 instances and ALB via script
      - name: Deploy EC2 and ALB
        run: |
          chmod +x ./ec2-alb-deploy.sh
          ./ec2-alb-deploy.sh

      # Step 5: Confirm Deployment (Optional)
      - name: Confirm EC2 and ALB Deployment
        run: |
          aws ec2 describe-instances --filters "Name=tag:Application,Values=Payment-Processing"
          aws elbv2 describe-load-balancers --names ALB-Payment-Processing
